# Generated by Django 5.0.3 on 2024-03-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_systematique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='certificat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='falsification',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='inconnu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='temps_ecoulé',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
